In [7]:
import numpy as np

# Perceptron

In [46]:
class Perceptron():
    def __init__(self, length, operation):  
        self.W = np.random.randn(length)  # shape (length,)
        self.b = 0
        self.lr = 0.01
        self.epochs = 1000
        self.length = length
        self.data = np.zeros((2**length, length))
        self.label = np.zeros((2**length))
        self.operation = operation
        
    # 真值表
    def truthTable(self):
        for j in range(self.length): # 第j列
            a = 0
            b = 2 **(self.length-1-j)
            for k in range(2**j):
                if b <= 2** self.length:
                    self.data[range(a,b),j] = 1
                    interval = 2**(self.length-j)
                    a += interval
                    b += interval
        print('truthTable:\n',self.data)
        
        if self.operation == 'and':
            self.label[0] = 1 
        elif self.operation == 'or':
            self.label[range(2**self.length-1)] = 1
        print('\nlabel:\n',self.label)
                    
    def predict(self, data):
        self.output = np.dot(data, self.W) + self.b 
        self.output[self.output>=0] = 1
        self.output[self.output<0] = 0
        return self.output
        
    def train(self):
        # 重置参数
        self.W = np.random.randn(self.length)
        self.b = 0
        self.truthTable()
        for t in range(self.epochs):
            for k in range(2**self.length):
                self.predict(self.data)
                self.W += self.lr*(self.label[k]-self.output[k])*self.data[k]
                self.b += self.lr*(self.label[k]-self.output[k])

        return self.W,self.b

# 训练

In [54]:
per = Perceptron(5, 'or')
W, b = per.train()
print('\nW:\n',W)
print('\nb:\n',b)

truthTable:
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 0.]
 [1. 1. 1. 0. 1.]
 [1. 1. 1. 0. 0.]
 [1. 1. 0. 1. 1.]
 [1. 1. 0. 1. 0.]
 [1. 1. 0. 0. 1.]
 [1. 1. 0. 0. 0.]
 [1. 0. 1. 1. 1.]
 [1. 0. 1. 1. 0.]
 [1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 0.]
 [1. 0. 0. 1. 1.]
 [1. 0. 0. 1. 0.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 0. 1.]
 [0. 1. 1. 0. 0.]
 [0. 1. 0. 1. 1.]
 [0. 1. 0. 1. 0.]
 [0. 1. 0. 0. 1.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 1. 1.]
 [0. 0. 1. 1. 0.]
 [0. 0. 1. 0. 1.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 1.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0.]]

label:
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 0.]

W:
 [1.42561542 0.81700386 0.31093223 0.75378878 0.01692054]

b:
 -0.01


# 测试

In [55]:
a = np.array([[1,1,1,1,1],
             [1,0,1,1,0],
             [0,0,0,1,0],
             [1,1,0,0,1],
             [0,0,0,0,0]])
print("测试数据：\n", a)
print("测试结果：\n", per.predict(a))
print("用以调整lr,epochs:\n",np.dot(a,W)+b)

测试数据：
 [[1 1 1 1 1]
 [1 0 1 1 0]
 [0 0 0 1 0]
 [1 1 0 0 1]
 [0 0 0 0 0]]
测试结果：
 [1. 1. 1. 1. 0.]
用以调整lr,epochs:
 [ 3.31426083  2.48033643  0.74378878  2.24953983 -0.01      ]


In [56]:
x1 = np.random.randn(5)
x2 = np.random.randn(1,5)
print(x1, "  ", x1.shape, "不区分行和列")
print(x2, "  ", x2.shape)

[-1.10631627 -1.97297607 -0.14097039  0.03665063  0.46587008]    (5,) 不区分行和列
[[-0.14224173  1.58005082 -0.65523859  1.04310415 -1.29172171]]    (1, 5)
