In [1]:
import numpy as np

# Hopfield

In [148]:
class Hopfield():
    def __init__(self, memory,row, col):
        # memory是待记忆的一组模式，用二维列表表示
        self.memory = memory
        self.row = row
        self.col = col
        self.N = len(memory[0])
        self.W = np.zeros((self.N, self.N), dtype = np.float32)
        
    def train(self):
        # 重置W
        self.W = np.zeros((self.N, self.N), dtype = np.float32)
        numArray = np.asarray(self.memory,dtype = np.int8)
        print(str(len(numArray))+" patterns")
        # 更新W
        for i in range(len(numArray)):
            v = numArray[i].reshape((1,self.N))
            self.W += np.dot(v.T,v)/self.N
        self.W[range(self.N),range(self.N)] = 0
        print('weights：\n',self.W)
        
    def predict(self, preArray):
        lastState = np.asarray(preArray,dtype = np.int8)
        for i in range(100):
            state = np.dot(self.W, lastState)
            state[state>=0] = 1
            state[state<0] = -1
            if (state==lastState).all():
                break
            else:
                lastState = state

        self.printNum(lastState)
#         print("迭代",i,"次收敛")
        return lastState
    
    def printNum(self, Num):
        a = np.asarray(Num)
        b = ['* ' if i==1 else '  ' for i in a]
        for i in range(self.row):
            print(''.join(b[:self.col]))
            b = b[self.col:]

# 定义数字

In [80]:
numDict = {}
numDict['zero'] = [-1,  1, 1, 1, -1,
                    1, -1,-1,-1,  1,
                    1, -1,-1,-1,  1,
                    1, -1,-1,-1,  1,
                    1, -1,-1,-1,  1,
                   -1,  1, 1, 1, -1]

numDict['one'] =  [-1, -1, 1, -1, -1,
                   -1,  1, 1, -1, -1,
                   -1, -1, 1, -1, -1,
                   -1, -1, 1, -1, -1,
                   -1, -1, 1, -1, -1,
                   -1, -1, 1, -1, -1]

numDict['two'] =  [-1,  1,  1,  1, -1,
                    1, -1, -1, -1,  1,
                   -1, -1, -1,  1, -1,
                   -1, -1,  1, -1, -1,
                   -1,  1, -1, -1, -1,
                    1,  1,  1,  1,  1]
     
numDict['three'] = [ 1,  1,  1,  1, 1,
                    -1, -1, -1, -1, 1,
                     1,  1,  1,  1, 1,
                     -1,  -1,  -1,  -1, 1,
                    -1, -1, -1, -1, 1,
                     1,  1,  1,  1, 1]
 
numDict['four'] =  [-1, -1,  1, 1, -1,
                    -1,  1, -1, 1, -1,
                     1, -1, -1, 1, -1,
                     1,  1,  1, 1,  1,
                    -1, -1, -1, 1, -1,
                    -1, -1, -1, 1, -1]

numDict['five'] = [ 1,  1,  1,  1,  1,
                    1, -1, -1, -1, -1,
                    1,  1,  1,  1,  1,
                    -1,  -1,  -1,  -1,  1,
                    -1, -1, -1, -1, 1,
                    1,  1,  1,  1,  1]

numDict['six'] =  [ -1, -1,  1,  1, -1,
                    -1,  1, -1, -1, -1,
                     1,  1,  1,  1, -1,
                     1, -1, -1, -1,  1,
                     1, -1, -1, -1,  1,
                    -1,  1,  1,  1, -1]
 
numDict['seven'] =[  1,  1,  1,  1,  1,
                    -1, -1, -1, -1,  1,
                    -1, -1, -1,  1, -1,
                    -1, -1,  1, -1, -1,
                    -1,  1, -1, -1, -1,
                     1, -1, -1, -1, -1]

numDict['eight'] =[ -1,  1,  1,  1, -1,
                     1, -1, -1, -1, 1,
                     -1,  1,  1,  1, -1,
                     1,  -1,  -1,  -1, 1,
                     1, -1, -1, -1, 1,
                    -1,  1,  1,  1, -1]

numDict['nine'] = [ -1,  1,  1,  1,  -1,
                     1, -1, -1, -1,  1,
                     1, -1, -1, -1,  1,
                     1,  1,  1,  1,  1,
                    -1, -1, -1,  1, -1,
                     1,  1,  1, -1, -1]

# "train"

In [153]:
memory = list(numDict.values())
Hop = Hopfield(memory,6,5)
Hop.train()

10 patterns
weights：
 [[ 0.0000000e+00  6.6666663e-02 -1.3333334e-01 -6.6666670e-02
   3.3333334e-01 -6.6666670e-02 -6.6666663e-02  6.6666670e-02
   6.6666670e-02 -5.7121117e-09 -5.7121117e-09  1.3333334e-01
   6.6666678e-02  6.6666670e-02  1.3333333e-01 -2.0000000e-01
   1.7384688e-09 -6.6666663e-02  1.7384688e-09 -6.6666670e-02
  -6.6666670e-02  1.3333334e-01  6.6666670e-02  1.7384688e-09
   6.6666663e-02  2.0000000e-01 -6.6666670e-02 -1.3333334e-01
  -6.6666670e-02  2.0000000e-01]
 [ 6.6666663e-02  0.0000000e+00  1.3333334e-01  2.0000000e-01
   6.6666663e-02  2.0000000e-01 -3.3333334e-01 -2.0000000e-01
  -2.0000000e-01  2.6666668e-01  1.9868216e-09 -5.7121117e-09
  -6.6666670e-02  6.6666663e-02  1.3333334e-01 -6.6666663e-02
  -1.3333334e-01 -6.6666678e-02 -1.3333334e-01  6.6666670e-02
  -6.6666663e-02 -5.7121117e-09 -2.0000000e-01 -1.3333334e-01
   6.6666678e-02  1.9999999e-01  2.0000000e-01  1.3333334e-01
   6.6666678e-02  6.6666663e-02]
 [-1.3333334e-01  1.3333334e-01  0.0000000e+

# 加入噪声

In [86]:
def addNoise(noiseType, originNum, noiseSize):
    noiseNum = np.asarray(originNum)
    if noiseType=='random':
        noisePosition = np.random.randint(30, size=noiseSize)
        for i in noisePosition:
            if noiseNum[i]==-1:
                noiseNum[i] = 1
            else:
                noiseNum[i] = -1
    elif noiseType=='half':
        for i in range(15,30):
            noiseNum[i] = -1
    else:
        print('no such noiseType.')
    return noiseNum

# 测试

In [152]:
noiseType = 'half'
noiseSize = 2
toPredictNum = 'one'
print('toPredictNum = ',toPredictNum ,'  noiseType = ',noiseType,'  noiseSize = ',noiseSize)
print("原始数字:")
Hop.printNum(numDict[toPredictNum])
toPredict = addNoise( noiseType, numDict[toPredictNum],noiseSize)
print("加入噪声:")
Hop.printNum(toPredict)
print("联想结果:")
Hop.predict(toPredict)

toPredictNum =  one   noiseType =  half   noiseSize =  2
原始数字:
    *     
  * *     
    *     
    *     
    *     
    *     
加入噪声:
    *     
  * *     
    *     
          
          
          
联想结果:
    *     
  * *     
    *     
    *     
    *     
    *     


array([-1., -1.,  1., -1., -1., -1.,  1.,  1., -1., -1., -1., -1.,  1.,
       -1., -1., -1., -1.,  1., -1., -1., -1., -1.,  1., -1., -1., -1.,
       -1.,  1., -1., -1.], dtype=float32)

In [150]:
# 不同shape的numpy数组的点积结果，与上面Hopfield无关
a = np.array([1,2,3])
print(a.shape)
print(a.T.shape)
b = a.reshape(1,3)
c = a.reshape(3,1)
print(b)
print(c)
print("np.dot(a,a)\n", np.dot(a,a))
print("np.dot(b,b.T)\n", np.dot(b,b.T))
print("np.dot(c.T,c)\n", np.dot(c.T,c))
print("np.dot(b.T,b)\n", np.dot(b.T,b))

(3,)
(3,)
[[1 2 3]]
[[1]
 [2]
 [3]]
np.dot(a,a)
 14
np.dot(b,b.T)
 [[14]]
np.dot(c.T,c)
 [[14]]
np.dot(b.T,b)
 [[1 2 3]
 [2 4 6]
 [3 6 9]]
